Pro4U/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from landing import views as landing_views
from review import views as review_views
from review.models import Review

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_views.homepage, name='homepage'),
    path('learn-more/', landing_views.learn_more, name='learn_more'),
    path('', include('reservation.urls')),
    path('', include('account.urls.login_urls')),
    path('', include('SearchHistory.urls')),
    path('', include('account.urls.profile_urls')),
    path('professional/<int:pk>/reviews/', review_views.ReviewListView.as_view(model=Review, paginate_by=10),
         name='reviews'),
    path('professional/<int:pk>/reviews/new/', review_views.ReviewCreateView.as_view(), name='review-create'),
    path('professional/<int:pk>/reviews/update/', review_views.ReviewUpdateView.as_view(), name='review-update'),
    path('', include('chatmessage.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/models.py
from django.db import models
from django.db.models import QuerySet


class TeamMember(models.Model):
    id = models.BigAutoField(primary_key=True, verbose_name="ID")
    name = models.CharField(max_length=30)
    img = models.CharField(max_length=50)
    alt = models.CharField(max_length=30)

    class Meta:
        db_table = 'TeamMember'

    @staticmethod
    def get_member(name: str) -> QuerySet:
        return TeamMember.objects.filter(name=name)

    def __str__(self):
        return self.name

professional/models.py
from django.db import models
from user.models import Profile
from django.db.models import Q


class Professions(models.TextChoices):
    Plumber = 'PLU', 'Plumber'
    Gardener = 'GAR', 'Gardener'
    Electrician = 'ELE', 'Electrician'
    Tinsmith = 'TIN', 'Tinsmith'
    Painter = 'PAI', 'Painter'
    Locksmith = 'LOC', 'Locksmith'
    Exterminator = 'EXT', 'Exterminator'
    GasTechnician = 'GAT', 'GasTechnician'
    AirConditioningTechnician = 'ACT', 'AirConditioningTechnician'
    RefrigeratorTechnician = 'RET', 'RefrigeratorTechnician'
    Cleaner = 'CLE', 'Cleaner'
    Handyman = 'HAN', 'Handyman'


class Professional(models.Model):
    professional_id = models.BigAutoField(primary_key=True)
    profile_id = models.OneToOneField(Profile, on_delete=models.CASCADE)
    profession = models.CharField(max_length=3, choices=Professions.choices, blank=True)
    description = models.TextField(blank=True)

    class Meta:
        db_table = 'professional'

    def __str__(self):
        return str(self)

    @staticmethod
    def filter_by_profession(profession):

        return Professional.objects.filter(profession=profession) if profession else []

    @staticmethod
    def filter_professionals_by_first_name(first_name):
        profile_ids = Profile.filter_by_first_name(first_name).values('profile_id') if first_name else []

        return Professional.objects.filter(Q(profile_id__in=profile_ids)) if profile_ids else []

    @staticmethod
    def filter_professionals_by_last_name(last_name):
        profile_ids = Profile.filter_by_last_name(last_name).values('profile_id') if last_name else []

        return Professional.objects.filter(Q(profile_id__in=profile_ids)) if profile_ids else []

    @staticmethod
    def filter_professionals_by_city(city):
        profile_ids = Profile.filter_by_city(city).values('profile_id') if city else []

        return Profile.objects.filter(Q(profile_id__in=profile_ids)) if city else []

landing/forms.py
# from django import forms

landing/views.py
import random

from enum import Enum

from django.db.models import Avg
from django.shortcuts import render

from landing.models import TeamMember
from account.models.professional import Professional

MAX_PROFESSIONALS = 48


class UserType(Enum):
    CLIENT = 'C'
    PROFESSIONAL = 'P'


def homepage(request):
    # TODO: add images for professionals
    db_professionals = Professional.objects.annotate(avg_rating=Avg('review__rating'))
    # Rounds average rating for each professional
    round_avg_rating(db_professionals)
    # Shuffle professionals randomly
    professionals = list(db_professionals)
    random.shuffle(professionals)
    # Context
    context = {
        'professionals': professionals[:MAX_PROFESSIONALS],  # Shows only the 'MAX_PROFESSIONALS' first professionals
    }
    return render(request, 'landing/homepage.html', context=context)


def round_avg_rating(professionals):
    """
    f(3.67124)=3.7 -> by rounding. It rounds the avg rating of a professional.
    """
    for professional in professionals:
        if professional.avg_rating is not None:
            professional.avg_rating = round(professional.avg_rating, 1)
        else:
            professional.avg_rating = 'N/A'


def learn_more(request):
    context = {'team_members': TeamMember.objects.all()}
    return render(request, 'landing/learn-more.html', context=context)

landing/templates/landing/base.html
{% load static %}
{% load custom_tags %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/x-icon" href="{% static '/img/Pro4U_logo.jpg' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/base_landing.css' %}">
    {% block head_content %}
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>
  <body class="bg-light text-dark">
    <!-- Navigation bar -->
    <nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <!-- Menu bar -->
        <div class="column-sm-auto">
          <a href="{% url 'homepage' %}" class="navbar-brand mr-5">
            <img src="{% static '/img/Pro4U_logo.jpg' %}" width="70" height="70" class="d-inline-block" alt="Pro4ULogo">
          </a>
          <a href="{% url 'homepage' %}" class="d-inline-block navbar-brand mb-0 h1 mr-5">
            Home
          </a>
          <a href="{% url 'learn_more' %}" class="d-inline-block navbar-brand mb-0 h1 mr-5">
            Learn More
          </a>
        </div>
        <!-- Search bar -->
        <div class="col-3">
          {% if request.user.is_authenticated %}
            <div class="input-group">
              <input type="search" class="form-control" placeholder="Search...">
              <button type="button" class="btn btn-warning">
                <!-- TODO: implement search functionality -->
                <i>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16" style="margin-bottom: 2px;">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                  </svg>
                </i>
              </button>
            </div>
          {% endif %}
        </div>
        <div class="dropdown">
          <!-- User bar (guest or logged-in) | Originally from AirBNB, with modifications -->
          <button class="user-btn" type="button" data-bs-toggle="dropdown" style="color: white; background-color: transparent; border: 0; width: 70px;">
            <svg class="d-inline" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="presentation" focusable="false">
              <path d="m16 .7c-8.437 0-15.3 6.863-15.3 15.3s6.863 15.3 15.3 15.3 15.3-6.863 15.3-15.3-6.863-15.3-15.3-15.3zm0 28c-4.021 0-7.605-1.884-9.933-4.81a12.425 12.425 0 0 1 6.451-4.4 6.507 6.507 0 0 1 -3.018-5.49c0-3.584 2.916-6.5 6.5-6.5s6.5 2.916 6.5 6.5a6.513 6.513 0 0 1 -3.019 5.491 12.42 12.42 0 0 1 6.452 4.4c-2.328 2.925-5.912 4.809-9.933 4.809z"></path>
            </svg>
          </button>
          <ul class="dropdown-menu" style="z-index: 100; left: -139%; top: 110%">
            {% if not request.user.is_authenticated %}
              <li>
                <a class="dropdown-item" href="#">
                  Sign up
                </a>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'login' %}">
                  Log in
                </a>
              </li>
            {% else %}
              <li>
                {% with professional=request.user|retrieve_professional_by_user_id %}
                  {% if professional %}
                    <a class="dropdown-item" href="{% url 'user_profile' %}">
                      Profile
                    </a>
                  {% endif %}
                {% endwith %}
                {% with client=request.user|retrieve_client_by_user_id %}
                  {% if client %}
                    <a class="dropdown-item" href="{% url 'user_profile' %}">
                      Profile
                    </a>
                  {% endif %}
                {% endwith %}
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <a class="dropdown-item" href="#">
                  Log out
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <!--Messages - Error message if the input is invalid, or success login-->
    <main>
      <div class="container col-md-4" style="width:400px; margin-top: 100px;">
        {% if messages %}
         {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      </div>
    </main>
    {% block content %}
    {% endblock %}
    <!--Footer-->
    <footer class="fixed-bottom py-3 border-top" style="background-color: var(--bs-light-bg-subtle); border-color: var(--bs-dark-rgb);">
      <div class="container d-flex justify-content-between align-items-center">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="mb-3 mb-md-0 text-muted">© 2023 Pro4U, RedHat Beyond</span>
        </div>
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <!--Facebook SVG icon-->
          <li class="ms-3">
            <a href="#">
              <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" style="fill: rgb(83, 87, 91);">
                <path d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"/>
              </svg>
            </a>
          </li>
          <!--Instagram SVG icon-->
          <li class="ms-3">
            <a href="#">
              <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" style="fill: rgb(83, 87, 91);">
                <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
              </svg>
            </a>
          </li>
          <!--Linkedin SVG icon-->
          <li class="ms-3">
            <a href="#">
              <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill: rgb(83, 87, 91);">
                <path d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"/>
              </svg>
            </a>
          </li>
          <!--Twitter SVG icon-->
          <li class="ms-3">
            <a href="#">
              <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" style="fill: rgb(83, 87, 91);">
                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
              </svg>
            </a>
          </li>
        </ul>
      </div>
    </footer>
  </body>
</html>

landing/templates/landing/homepage.html
{% extends "account/profile.html" %}
{% load static %}
{% load custom_tags %}

{% block title %}
  Pro4U Homepage
{% endblock %}

{% block center-content %}
  <div class="container">
    <div class="row">
      {% if request.user.is_authenticated %}
        {% with client=request.user|retrieve_client_by_user_id %}
          {% if client %}
            {% for professional in professionals %}
              <div class="col-md-3" style="margin-bottom: 18px;">
                <div style="">
                  <a href="{% url 'show_business_page' professional.professional_id %}" style="text-decoration: none;">
                    <!-- TODO: add link to profile -->
                    {% if professional.thumbnail %}
                      <img class="img-fluid" src="{% static professional.thumbnail %}">
                    {% else %}
                      <img class="img-fluid" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png">
                    {% endif %}
                    <div class="d-flex justify-content-between align-items-center mt-2">
                      <div class="text-left text-dark fw-semibold">
                        {{ professional.profile_id.user_id.get_full_name }}
                      </div>
                      <div class="text-right text-dark fw-semibold">
                        <strong style="color: rgb(255, 215, 0);">&#9733;</strong> {{ professional.avg_rating }}
                      </div>
                    </div>
                    <div class="text-body-secondary">
                      {{ professional.profile_id.city }}
                    </div>
                    <div class="text-body-secondary">
                      {{ professional.get_profession_display }}
                    </div>
                  </a>
                </div>
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      {% else %}
        <div class="vstack gap-2 col-md-5 mx-auto text-center text-danger">
          <h1>
            This page is only available to authorized clients
          </h1>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

landing/templates/landing/learn-more.html
{% extends "landing/base.html" %}
{% load static %}

{% block title %}
  Pro4U Learn More
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row" style="margin-top: 156px;">
      <div class="col-md-6">
        <h2>Pro4U</h2>
        <h2>Innovative Solution!</h2>
        <div class="list-group">
          <a class="list-group-item list-group-item-action list-group-item-light">
            Pro4U (professional for you) is an application that works like a social network. It gives you an option to schedule
            appointments with private professionals throughout the country, including cosmetologists, plumbers, tinsmiths, glaziers,
            gardeners, and more.
          </a>

        <a class="list-group-item list-group-item-action list-group-item-light">
          Professionals can add the types of work done, products for sale, appointment availability, and prices.
        </a>
        <a class="list-group-item list-group-item-action list-group-item-light">
          Users can add opinions about professionals and schedule appointments during working hours.
        </a>
        </div>
      </div>
      <div class="col-md-6">
        <div class="row">
          {% for member in team_members %}
            <div class="col-4 mb-4">
              <div class="card">
                <img src="{% static member.img %}" class="card-img-top" alt="{{ member.alt }}" style="height: 194px; width: 100%; object-fit: cover;">
                <div class="card-body">
                  <h6 class="card-title">{{ member.name }}</h6>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}